[package]
name = "lunex"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3


[dependencies]
ahash = "0.8.3"
#bevy = "0.10.1"
bevy = { version = "0.10.1", features = ["dynamic_linking"] }
rand = "0.8.5"
